name: Sync to Hugging Face Hub

on:
  push:
    branches: [ main ]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs install

          git reset --hard HEAD
          git clean -fd || true


          git lfs migrate import --everything --include="*.png,*.psd,*.webp,*.jpg,*.jpeg,*.gif,*.ico,*.woff,*.woff2,*.ttf,*.otf"

          git push --force https://token:$HF_TOKEN@huggingface.co/spaces/myarenaosx/openwa main
