name: Sync to Hugging Face Hub

on:
  push:
    branches: [ main ]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # تهيئة أداة الملفات الكبيرة
          git lfs install
          
          # تحويل الملفات القديمة والموجودة في الـ History برمجياً إلى ملفات LFS لكي يقبلها الخادم
          git lfs migrate import --everything --include="*.png,*.psd"
          
          # الرفع القسري بعد إصلاح التاريخ
          git push --force https://token:$HF_TOKEN@huggingface.co/spaces/myarenaosx/openwa main
